services:
  nginx:
    image: nginx:1.29.1
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

  api:
    container_name: api
    tty: true
    build: ./api
    volumes:
      - ./api:/go/src/api
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
      - ./api/.env

  db:
    image: postgres:17-alpine
    container_name: db
    tty: true
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=Asia/Tokyo
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

volumes:
  postgres-data:
